apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cloudforet-console-api-v2
  namespace: cloudforet-core
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/managed-by-origin-location: url:https://github.com/sang-w0o/console-api-v2/blob/master/backstage/component-info.yaml
    backstage.io/kubernetes-id: 'cloudforet-console-api-v2'
    backstage.io/kubernetes-namespace: doodle-core
    backstage.io/kubernetes-label-selector: 'backstage.io/kubernetes-id=cloudforet-console-api-v2'
spec:
  type: coreService
  lifecycle: experimental
  owner: mino@mz.co.kr

