apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: console-api-v2
build:
  platforms: ["linux/amd64"]
  artifacts:
    - image: ${IMAGE_REPOSITORY}/console-api-v2
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
    - name: console-api-v2
      chartPath: deploy/helm
      valuesFiles:
      - ${VALUES_LOCATION}/console-api-v2.yaml

